window:
  title: "Pong Go"
  width: 800
  height: 600
  resizable: true

screen:
  width: 640
  height: 480
  color: "#050505"
  font_size: 64

paddle:
  color: "FFFFFF"

ball:
  color: "FFFFFF"

line:
  color: "AFAFAFAF"

